services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - 7878:7878

  web:
    build: ./client
    ports:
      - 5173:5173
    working_dir: /usr/src/app
    volumes:
      - ./client/:/usr/src/app
    depends_on:
      - api
