services:
  api:
    image: alexwillmcleod/freelance-project-tracker-api
    build: /api
    expose:
      - 80

  web:
    image: alexwillmcleod/freelance-project-tracker-web
    build: /client
    ports:
      - 5173:5173
    depends_on:
      - api
